# Generated by Django 2.1.1 on 2019-01-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10, verbose_name='request_method')),
                ('interface_url', models.URLField(max_length=100, verbose_name='interface_url')),
                ('header_name', models.CharField(max_length=100, verbose_name='header_name')),
                ('header_value', models.CharField(max_length=100, verbose_name='header_value')),
                ('para_name', models.CharField(blank=True, max_length=100, verbose_name='parameter_name')),
                ('para_value', models.CharField(blank=True, max_length=100, verbose_name='parameter_value')),
                ('encryption_algorithm', models.CharField(blank=True, max_length=60, verbose_name='encryption_algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='user_name')),
                ('user_email', models.EmailField(max_length=255, verbose_name='email_address')),
                ('user_password', models.CharField(max_length=16, verbose_name='user_password')),
            ],
        ),
    ]
