# Generated by Django 2.1.1 on 2019-01-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='user_name')),
                ('user_email', models.EmailField(max_length=255, verbose_name='email_address')),
                ('user_phone', models.CharField(max_length=11, verbose_name='user_phone')),
                ('user_password', models.CharField(max_length=16, verbose_name='user_password')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
