# Generated by Django 2.1.1 on 2019-01-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190110_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_phone',
        ),
    ]
